[build]
  # Build command for the frontend
  command = "cd frontend && npm run build"
  
  # Output directory for the built frontend
  publish = "frontend/dist"
  
  # Functions directory for serverless functions
  functions = "api"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

# Redirects for API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirects for auth routes
[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/auth"
  status = 200

# Redirects for frontend routes (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for CORS
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[headers]]
  for = "/auth/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
